systemd support for agents

diff --git a/debian/neutron-metadata-agent.init b/debian/neutron-metadata-agent.init
--- a/debian/neutron-metadata-agent.init
+++ b/debian/neutron-metadata-agent.init
@@ -19,7 +19,7 @@ DESC="OpenStack Neutron Metadata Agent"
 NAME=neutron-metadata-agent
 DAEMON=/usr/bin/${NAME}
 DAEMON_ARGS="--config-file=/etc/neutron/neutron.conf --config-file=/etc/neutron/metadata_agent.ini"
-PIDFILE=/var/run/$NAME.pid
+PIDFILE=/var/run/neutron/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
@@ -32,6 +32,9 @@ SCRIPTNAME=/etc/init.d/$NAME
 
 [ "x$USE_SYSLOG" = "xyes" ] && DAEMON_ARGS="$DAEMON_ARGS --use-syslog"
 [ "x$USE_LOGFILE" != "xno" ] && DAEMON_ARGS="$DAEMON_ARGS --log-file=/var/log/neutron/metadata-agent.log"
+
+mkdir -p /var/run/neutron
+chown neutron:neutron /var/run/neutron
 
 do_start()
 {
@@ -70,6 +73,36 @@ case "$1" in
   status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
+  systemd-start)
+       do_start
+       ;;
+  systemd-stop)
+       do_stop
+       ;;
+  restart|force-reload)
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        do_stop
+        case "$?" in
+            0|1)
+                do_start
+                case "$?" in
+                    0) log_end_msg 0 ;;
+                    1) log_end_msg 1 ;; # Old process is still running
+                    *) log_end_msg 1 ;; # Failed to start
+                esac
+                ;;
+            *)
+            # Failed to stop
+                log_end_msg 1
+                ;;
+        esac
+        ;;
+
+  *)
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
+esac
   restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
         do_stop
